# Base image
FROM node:18.15.0

# Set working directory
WORKDIR /src

# Install dependencies
COPY package.json .
COPY package-lock.json .
RUN npm install

# Copy source files
COPY . .

# Build the app
RUN npm run build

# Expose port
EXPOSE 3000

# Run the app
CMD ["npm", "run", "dev"]
