version: "3"
services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=aws-database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
    volumes:
      - ./data:/var/lib/mysql
